#! /bin/bash
RUCE=~/RUCE/build/src/RUCE_CLI
echo $* >> /tmp/ruce.log
pitchconverter(){
TEMPO=`echo $1 | cut -d Q -f 2`
echo -n '!'$TEMPO' '
for i
do
PITCH=`echo $1 | cut -d Q -f 1`
echo $PITCH | convert-c
shift 1
done
}
P1="$1 $2 $3 $4 $5 $6 $7 $8 $9"
shift 9
P1="$P1 $1 $2"
echo $P1
shift 2
echo $*
P2="`pitchconverter $*`"
$RUCE $P1 $P2 >> /tmp/ruce.log 2>&1
